apiVersion: dbaas.redhat.com/v1alpha1
kind: DBaaSProvider
metadata:
  name: atlas-provider-registration
  labels:
    related-to: dbaas-operator
    type: dbaas-provider-registration
spec:
  provider:
    name: Red Hat DBaaS / MongoDB Atlas
    displayName: MongoDB Atlas
    displayDescription: Some nice description show to dev users in UX when selecting which provider from catalog.
    icon:
      base64data: <base64-encoded image data>
      mediatype: image/png
  inventoryKind: MongoDBAtlasInventory
  connectionKind: MongoDBAtlasConnection
  instanceKind: MongoDBAtlasInstance
  credentialFields:
    - key: organizationId
      displayName: Organization ID
      type: string
      required: true
    - key: publicApiKey
      displayName: Organization Public Key
      type: string
      required: true
      helpText: string
    - key: privateApiKey
      displayName: Organization Private Key
      type: maskedstring
      required: true
      helpText: string
  allowsFreeTrial: true
  instanceParameterSpecs:
    - name: clusterName
      displayName: Cluster Name
      type: string
      required: true
    - name: ProjectName
      displayName: Atlas Project Name
      type: string
      required: true
    - name: clusterType
      displayName: Cluster Type
      type: string
      required: false
      defaultValue: Shared
    - name: providerName
      displayName: Cloud Provider
      type: string
      required: false
      defaultValue: AWS
    - name: regionName
      displayName: Cloud Region
      type: string
      required: false
      defaultValue: US_EAST_1
    - name: instanceSizeName
      displayName: Cluster Size Name
      type: string
      required: false
      defaultValue: M0
